### PR TITLE
GH-1 releasing the project

### LINKED ISSUE #1: Release project
Release the project from Zalando Github Enterprise.

### PR DESCRIPTION
**Pull request by sina-golesorkhi**
closes #1

### CODE REVIEW

**Comment by waleed-madanat** [comment]
:+1:

**Comment by perploug** [comment]
Looks good to me 👍

**Comment by perploug** [comment]
👍

**Comment by sina-golesorkhi** [comment]
👍

**Comment by sina-golesorkhi** [comment]
👍

**Comment by waleed-madanat** [comment]
:+1:

**Pull request merged**
